In [1]:
import pandas as pd

In [3]:
pd.read_csv("/home/xrh1/Desktop/covidlombardy/ki_cv_all/per100kdataset_from_2020-02-20_to_2020-08-20.csv")

,NUTS,air passengers per100k,GDP per100k,farm labour force per100k,deaths per100k,hosp discharges resp diseases per100k,stock of vehicles per100k,thousand hours worked per100k,students tertiary ed per100k,health personnel per100k,...,compensation of employees per100k,hospital beds,unemployment rate,pop density,life expectancy,education and training,NEET rate,covid_severity,covid_density_by100k,Covid_Cases
0,AT11,2048.605922,3149.278621,2095.531796,1152.372672,1293.999375,86547.840617,68999.714709,2292.518578,433.710552,...,1462.117404,587.21,4.2,77.8,81.9,9.3,7.775,below_than_avg,153.853469,453
1,AT12,1878.242841,3663.641648,1820.354845,1035.987335,1261.483346,81871.082541,70017.164533,1968.310626,470.169276,...,1689.201425,671.36,4.2,88.9,81.7,9.3,7.000,below_than_avg,220.805599,3719
2,AT13,315.605993,5250.512377,110.402362,845.022816,1535.900912,41839.669609,86993.398357,10070.735997,684.285349,...,2544.225041,751.91,10.6,4808.9,81.1,16.5,9.900,below_than_avg,353.078264,6748
3,AT21,37.413615,3831.430287,1341.545325,1074.483380,1933.927557,78155.972015,78039.455329,2766.291402,484.951710,...,1799.238544,803.93,4.7,59.9,82.2,10.1,7.900,below_than_avg,108.321322,608
4,AT22,83.039486,4078.193510,1720.160944,1018.216536,1950.425026,75984.017908,82089.546251,4977.154112,520.621472,...,1965.909684,801.30,4.4,76.6,82.2,11.3,7.600,below_than_avg,184.532191,2300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,SI04,172.616531,2749.070391,2297.537076,891.299785,1369.585148,62507.167251,88545.381880,5422.006750,379.776452,...,1421.134128,517.78,4.4,126.9,82.8,9.3,5.800,below_than_avg,49.605914,494
133,SK01,341.252584,3939.646830,385.309263,905.327423,4762.014005,75997.174399,121364.054529,8013.984635,643.675552,...,1609.745935,715.17,3.4,328.8,79.3,4.7,7.900,below_than_avg,114.099332,764
134,SK02,77.887171,1584.106082,1208.471141,1041.346820,1748.338890,53574.969075,76593.657610,1848.237080,277.608411,...,620.263166,471.62,4.7,123.0,78.0,2.0,7.700,below_than_avg,53.185890,970
135,SK03,106.262413,1408.905695,1052.525275,1029.260502,2385.279968,46436.487543,71761.203185,1774.930150,331.167690,...,581.700124,583.78,6.7,82.7,77.2,3.2,10.200,below_than_avg,43.761712,585
136,SK04,34.158545,1214.027858,731.705519,885.971897,1958.959664,40408.452642,58639.838693,1825.454751,347.360454,...,461.394701,630.22,10.5,103.9,77.6,2.7,15.400,below_than_avg,47.797388,778